[package]
name = "proto"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
prost = "0.14.1"
prost-types = "0.14.1"

[build-dependencies]
prost-build = "0.14.1"
